name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: [1.14.x, 1.15.x]

    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: go build

    - name: Check formatting
      if: matrix.os != 'windows-latest'
      run: diff -u <(echo -n) <(gofmt -d -s .)

    - name: Check go vet
      run: go vet
#
#    - name: Test
#      run: go test -v ./...
